spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: configmapcontroller
        image: fabric8/configmapcontroller:${configmapcontroller.version}
        resources:
          limits:
            memory: '${k8s.memory.limit}'
            cpu: '${k8s.cpu.limit}'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      serviceAccountName: configmapcontroller
