metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "exposecontroller"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: exposecontroller
        image: fabric8/exposecontroller:${exposecontroller.version}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: 86164
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/exposecontroller
      volumes:
      - name: config-volume
        configMap:
          name: exposecontroller
      serviceAccountName: exposecontroller
