spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: "funktion/funktion:${funktion.version}"
        imagePullPolicy: "IfNotPresent"
        name: "funktion"
        command: ["/bin/operator", "operate"]
        resources:
          limits:
            memory: '250Mi'
            cpu: '250m'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      serviceAccountName: "funktion-operator"
