spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: "funktion/funktion:${funktion.version}"
        imagePullPolicy: "IfNotPresent"
        name: "funktion"
        command: ["/bin/operator", "operate"]
      serviceAccountName: "funktion-operator"
