metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "exposecontroller"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: "funktion"
        image: "funktion/funktion:${funktion.version}"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/operator", "operate"]
        resources:
          limits:
            memory: '${k8s.memory.limit}'
            cpu: '${k8s.cpu.limit}'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      - name: configmapcontroller
        image: fabric8/configmapcontroller:${configmapcontroller.version}
        command: ["/configmapcontroller", "--healthz-port", "10354"]
        resources:
          limits:
            memory: '${k8s.memory.limit}'
            cpu: '${k8s.cpu.limit}'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      - name: exposecontroller
        image: fabric8/exposecontroller:${exposecontroller.version}
        resources:
          limits:
            memory: '${k8s.memory.limit}'
            cpu: '${k8s.cpu.limit}'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/exposecontroller
      volumes:
      - name: config-volume
        configMap:
          name: exposecontroller
      serviceAccountName: "funktion-operator"
