metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "exposecontroller"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: "funktion"
        image: "funktion/funktion:${funktion.version}"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/operator", "operate"]
        resources:
          limits:
            memory: '300Mi'
            cpu: '300m'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      - name: exposecontroller
        image: fabric8/exposecontroller:${exposecontroller.version}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/restarteveryday
          initialDelaySeconds: 86164
        resources:
          limits:
            memory: '250Mi'
            cpu: '250m'
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/exposecontroller
      volumes:
      - name: config-volume
        configMap:
          name: exposecontroller
      serviceAccountName: "funktion-operator"
